pipeline:
  build:
    image: python:3.6
    commands:
      - python -V
      - pip install virtualenv
      - virtualenv venv
      - . ./venv/bin/activate
      - pip install -r requirements.txt -r requirements-test.txt
      - ./test.sh