version: "3.2"

volumes:
  mongodb:

services:
  database:
    image: "mongo:3"
    ports:
      - "27017:27017"
    volumes:
      - "mongodb:/data/db"

  bot:
    image: "registry.gitlab.com/lu-ci/apex-sigma:latest"
    build:
      context: .
    volumes:
      - type: bind
        source: "./config"
        target: "/app/config"
        read_only: true
    depends_on:
      - "database"
