name:             Autorole Controls

category:         roles

enabled:          true

commands:
  - name:         autorole
    alts:
      - "autorank"
    enabled:      true
    usage:        "{pfx}{cmd} Newcomer"
    requirements:
      - "manage_roles"
    description:
      Sets which role should be given to joining members.
      When a new user enters the server, this role will be assigned to them.
      The role can not be something that is above the bot's highest role.
      If you want to disable the autorole, input "disable" as the role name.

  - name:         autoroletimeout
    alts:
      - "arltimeout"
      - "arlt"
    enabled:      true
    usage:        "{pfx}{cmd} 600"
    description:
      Sets the number of seconds the bot should wait before assigning the set auto-role.
      To disable the timeout, simply input 0 as the timeout, nothing special.

  - name:         bindinvite
    alts:
      - "bindinvs"
      - "binvite"
      - "binv"
    enabled:      true
    usage:        "{pfx}{cmd} aEUCHwX Cheese Lovers"
    requirements:
      - "manage_guild"
      - "manage_roles"
      - "create_instant_invite"
    description:
      Binds an invite to a role.
      When a member joins using that invite the stated role will be given to them.

  - name:         syncinvites
    alts:
      - "syncinvs"
      - "sinvs"
    enabled:      true
    requirements:
      - "manage_guild"
    usage:        "{pfx}{cmd}"
    description:
      Forces an update of the invite cache for your server.
      For use if you have suspicions that the bound role counters are out of sync.

  - name:         boundinvites
    alts:
      - "boundinvs"
      - "binvites"
      - "binvs"
    enabled:      true
    usage:        "{pfx}{cmd}"
    description:
      Lists all the invites that are bound and what they are bound to.

  - name:         unbindinvite
    alts:
      - "unbinvite"
      - "unbindinv"
      - "unbinv"
    enabled:      true
    usage:        "{pfx}{cmd} aEUCHwX"
    requirements:
      - "manage_guild"
      - "manage_roles"
      - "create_instant_invite"
    description:
      Unbinds a previously bound invite from it's bound role.
      If the invite with that ID no longer exists on your server add ":f" to the end to force remove it.
      Please not that if you are force removing an invite that it is case sensitive.

events:
  - name:         autorole_control
    type:         member_join
    enabled:      true

  - name:         bound_role_cacher
    type:         ready
    enabled:      true

  - name:         bound_role_control
    type:         member_join
    enabled:      true
