name:             SelfRole Controls

category:         roles

enabled:          true

commands:
  - name:         addselfrole
    alts:
      - "addrank"
      - "asr"
    enabled:      true
    usage:        "{pfx}{cmd} Cheese Lover"
    requirements:
      - "manage_roles"
    description:
      Sets a role as self assignable.
      Roles that are self assignable, any user can assign to themselves.
      To assign a self assignbale role to yourself, use the togglerole command.

  - name:         delselfrole
    alts:
      - "delrank"
      - "rsr"
      - "dsr"
    enabled:      true
    usage:        "{pfx}{cmd} Meat Lover"
    requirements:
      - "manage_roles"
    description:
      Removes a role from the list of self assignable roles.

  - name:         listselfroles
    alts:
      - "listranks"
      - "listroles"
      - "ranks"
      - "roles"
      - "lsrl"
    enabled:      true
    description:
      Lists all self assignable roles present on the server.

  - name:         togglerole
    alts:
      - "togglerank"
      - "rank"
      - "trl"
    enabled:      true
    usage:        "{pfx}{cmd} Overlord"
    requirements:
      - "manage_roles"
    description:
      Toggles a self assignable role.
      If you don't have the role, it will be given to you.
      If you do have the role, it will be removed from you.

  - name:         colorme
    alts:
      - "clrme"
      - "cme"
    enabled:      true
    usage:        "{pfx}{cmd} #1abc9c"
    requirements:
      - "manage_roles"
    description:
      If the current guild has color roles enabled, you can color yourself with this command.
      For more information about how this works, use the help command on the colorroles command.
      Any other (prefixed) color roles on you will be removed prior to adding the new one.
